AccessDeniedException remains uncaught


If i throw a new AccessDeniedException (or in normal flow if a user doesn't have access to a page), it isn't getting resolved by Twig. In fact, I get an apache 500 with "uncaught exception":
Uncaught exception 'Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException'
with message 'Access Denied.'

Symfony/Component/Security/Http/Firewall/AccessListener.php:70
throw new \Symfony\Component\Security\Core\Exception\AccessDeniedException()
The below resolves correctly:
throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException()
